environment: develop
vesion: v1
spring:  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
cache:
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
app:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password:
    configuration:
      maximum-pool-size: 30