environment: develop
spring:
  cloud:
    gateway:
      routes:
        - id: account-app
          uri: http://localhost:8081
          predicates:
            - Method=GET,POST
        - id: cache-app
          uri: http://localhost:8082
          predicates:
            - Method=GET,POST
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}